version: '3'
services:
  neighborhub-backend:
    image: neighborhub:latest
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db_neighborhub
      MYSQL_PORT: 3306
      MYSQL_USER: neighborhub
      MYSQL_PASSWORD: neighborhub102
      MYSQL_DATABASE: neighborhub
    depends_on:
      - db_neighborhub


  db_neighborhub:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql_neighborhubContainer
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: neighborhub102
      MYSQL_DATABASE: neighborhub
      MYSQL_USER: neighborhub
      MYSQL_PASSWORD: neighborhub102
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: