
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:neighborhub}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Ho_Chi_Minh
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh
app:
  cors:
    allowedOrigins: http://localhost:4176,http://localhost:4200,http://localhost:4201,http://localhost:5173,http://localhost:5100,http://localhost:${SERVER_PORT:8080},https://167.71.212.203:${SERVER_PORT:8080},https://167.71.212.203,http://167.71.212.203:${SERVER_PORT:8080},http://167.71.212.203,http://apineighborhub.vn:8081,http://apineighborhub.vn:8081,http://adminneighborhub.vn:8081
  api:
    version:
      v1: /api/v1
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: http://apineighborhub.vn:8081
  auth:
    tokenSecret: 186e4b79e23b663a99f7824f3c48066c517258bbaa8237d45fec6b31e0cca51b
    refreshTokenExpirationMsec: 604800000
    accessTokenExpirationMsec: 604800000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html